using System.Diagnostics;
using System.IO;
using Presentation.Web.Models;

namespace Presentation.Web.Services
{
    public class PythonCaller : IPythonCaller
    {
        public void callPython(string pathToPython, PresentationFile presentation)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = pathToPython;
            start.Arguments = string.Format("\"{0}\" \"{1}\" \"{2}\" \"{3}\"", @"PythonScripts\PowerPointScript", presentation.ChartTitle, presentation.FirstValue,                                       presentation.SecondValue);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start)) { }
        }
    }
}